SeeYouOnTheBeach.Web/Controllers/BeachDetailController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Microsoft.Ajax.Utilities;
using SeeYouOnTheBeach.Web.Repository;
using SeeYouOnTheBeach.Web.ViewModels;
using SharpKml.Dom;
using Newtonsoft.Json;
using SeeYouOnTheBeach.Web.OpenData;
using SeeYouOnTheBeach.Web.Utilities;

namespace SeeYouOnTheBeach.Web.Controllers
{
    public class BeachDetailController : Controller
    {
        private readonly DataRepository _dataRepository;

        public BeachDetailController()
        {
            _dataRepository = new DataRepository();
        }

        public async Task<ActionResult> Index(int? beachid = 1)
        {
            if (beachid == null)
            {
                beachid = 1;
            }
            var barbecues = _dataRepository.GetBarbecueDataById(beachid.Value).Select(MapLocation.MapBarbecueFromBbqList).ToArray();
            var sport = _dataRepository.GetSportDataById(beachid.Value).Select(MapLocation.MapSportFromPlacemark).ToArray();
            var hospital = _dataRepository.GetHospitalDataById(beachid.Value).Select(MapLocation.MapHpspitalFromPlacemark).ToArray();
            var toilet = _dataRepository.GetToiletAndDrinkingData().Where(d => d.State == beachid.ToString()).Select(MapLocation.MapToiletFromToiletDetails);
            var bikeShare = _dataRepository.GetBikeShareDataById(beachid.Value).Select(MapLocation.MapBikeShareFromRow);
            var weather = await _dataRepository.GetWeatherDataByBeachId(beachid.Value);
                 
            var viewModel = new BeachDetailViewModel
            {
                Beaches = _dataRepository.GetBeaches(),
                Photos = _dataRepository.GetPhotosById(beachid.Value),              
                Sport = JsonConvert.SerializeObject(sport).ProceedQuotationAndBreaks(),
                Beach = _dataRepository.GetBeaches().FirstOrDefault(b => b.BeachId == beachid),
                Barbecue = JsonConvert.SerializeObject(barbecues).ProceedQuotationAndBreaks(),
                Hospital = JsonConvert.SerializeObject(hospital).ProceedQuotationAndBreaks(),
                BikeShare = JsonConvert.SerializeObject(bikeShare).ProceedQuotationAndBreaks(),
                Weather = weather.Replace("http","https").ProceedQuotationAndBreaks(),
                Toilet = JsonConvert.SerializeObject(toilet).ProceedQuotationAndBreaks()
            };
            
            return View(viewModel);
        }
    }
}

SeeYouOnTheBeach.Web/Views/Shared/_Layout.cshtml
@model SeeYouOnTheBeach.Web.ViewModels.BaseViewModel

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jsslider")
    @Scripts.Render("~/bundles/canvasjs")


    <script type="text/javascript">
        var appInsights = window.appInsights || function (config) {
            function r(config) { t[config] = function () { var i = arguments; t.queue.push(function () { t[config].apply(t, i) }) } } var t = { config: config }, u = document, e = window, o = "script", s = u.createElement(o), i, f; for (s.src = config.url || "//az416426.vo.msecnd.net/scripts/a/ai.0.js", u.getElementsByTagName(o)[0].parentNode.appendChild(s), t.cookie = u.cookie, t.queue = [], i = ["Event", "Exception", "Metric", "PageView", "Trace", "Ajax"]; i.length;) r("track" + i.pop()); return r("setAuthenticatedUserContext"), r("clearAuthenticatedUserContext"), config.disableExceptionTracking || (i = "onerror", r("_" + i), f = e[i], e[i] = function (config, r, u, e, o) { var s = f && f(config, r, u, e, o); return s !== !0 && t["_" + i](config, r, u, e, o), s }), t
        }({
            instrumentationKey: "a14a8979-8402-49c3-b7d3-867747dccb26"
        });

        window.appInsights = appInsights;
        appInsights.trackPageView();
    </script>
</head>
<body style="background-color:#FDFDFD;">
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#layoutDropdown">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("See U On The Beach", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                
            </div>
            <div class="navbar-collapse collapse" id="layoutDropdown">
                <ul class="nav navbar-nav">
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                            Explore Beaches
                            <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                            @if (Model?.Beaches != null)
                            {
                                foreach (var item in Model.Beaches)
                                {
                                    <li>@Html.ActionLink(item.BeachName, "Index", "BeachDetail", new {beachid = item.BeachId}, null)</li>
                                }
                            }

                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <div>
        @RenderBody()
    </div>
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>